services:
  - type: web
    name: pix-dupe-detect-api
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/api/server.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: API_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DUPE_ROOT
        sync: false
      - key: TRASH_DIR
        sync: false
      - key: THUMBNAIL_DIR
        sync: false
      - key: SIMILARITY_THRESHOLD
        value: "8"
      - key: CONCURRENCY
        value: "8"


    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

    headers:
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-XSS-Protection"
        value: "1; mode=block"
      - path: "/*"
        name: "Strict-Transport-Security"
        value: "max-age=31536000; includeSubDomains"
      - path: "/*"
        name: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"

  - type: worker
    name: dupe-scanner-worker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: node dist/worker/index.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false
      - key: DUPE_ROOT
        sync: false
      - key: UPLOAD_DIR
        sync: false
      - key: THUMBNAIL_DIR
        sync: false
      - key: TRASH_DIR
        sync: false
      - key: QUEUE_URL
        sync: false
      - key: MAX_CONCURRENCY
        value: "8"
      - key: HASH_ALGO
        value: "phash"
      - key: SIMILARITY_THRESHOLD
        value: "8"
