services:
  - type: web
    name: pix-dupe-detect-ui
    env: static
    rootDir: pix-dupe-detect-main
    buildCommand: npm ci && npm run build
    staticPublishPath: dist

    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_APP_NAME
        value: "PIX DUPE DETECT"
      - key: VITE_APP_ENVIRONMENT
        value: "production"
      - key: VITE_MAX_FILE_SIZE
        value: "10485760"
      - key: VITE_ALLOWED_FILE_TYPES
        value: "image/jpeg,image/png,image/gif,image/webp"

    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

    headers:
      - path: "/*"
        name: "X-Content-Type-Options"
        value: "nosniff"
      - path: "/*"
        name: "X-Frame-Options"
        value: "DENY"
      - path: "/*"
        name: "X-XSS-Protection"
        value: "1; mode=block"
      - path: "/*"
        name: "Strict-Transport-Security"
        value: "max-age=31536000; includeSubDomains"
      - path: "/*"
        name: "Referrer-Policy"
        value: "strict-origin-when-cross-origin"

  - type: worker
    name: dupe-scanner-worker
    env: node
    buildCommand: npm ci && npm run build --if-present
    startCommand: node dist/worker.js
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: DATABASE_URL
        sync: false
      - key: DUPE_ROOT
        sync: false
      - key: UPLOAD_DIR
        sync: false
      - key: THUMBNAIL_DIR
        sync: false
      - key: TRASH_DIR
        sync: false
      - key: QUEUE_URL
        sync: false
      - key: MAX_CONCURRENCY
        value: "8"
      - key: HASH_ALGO
        value: "phash"
      - key: SIMILARITY_THRESHOLD
        value: "8"
