name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK_URL }}" ]; then
            echo "RENDER_DEPLOY_HOOK_URL not set; skipping" && exit 0
          fi
          curl -fsSL -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"